apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-lab-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-lab
  template:
    metadata:
      labels:
        app: docker-lab
    spec:
      containers:
        - name: docker-lab-app
          image: docker-lab-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
